# Directory used to build the styleguide. `./assets/sass/musashi` when editing musashi and `./assets/sass/theme` when theming
source: assets/sass/musashi

# Directory to build the styleguide
destination: styleguide

# Hologram theme
documentation_assets: bower_components/Cortana
custom_markdown: bower_components/Cortana/CortanaMarkdownRenderer.rb

# To have a custom index page build with your README.md
index: README

dependencies:
  - build/js
  - build/css
  - build/fonts
  - assets/components

# List all css to include for the styleguide render examples (path from styleguide directory)
css_include:
  - 'css/musashi.css'

# List all web components to include
components_include:
  - 'components/grid.html'

# List all js to include for the styleguide render examples (path from styleguide directory)
js_include:
  - 'js/vendors.min.js'
  - 'js/musashi.js'

# String who is used to split the category name and create category wrapper
name_scope: ' - '